### ISSUE TITLE
DAYS_BACK nefunguje v ParovacFaktur

### ISSUE THREAD

**Issue by Antis0cial** [VitexSoftware/php-flexibee-matcher#1]
V konfiguraci `/etc/flexibee/matcher.json` je možné nastavit, kolik dní zpětně se mají vyhledávat faktury klíčem `DAYS_BACK`. V třídě `ParovacFaktur` sice konfigurace načte do pole `$this->config`, ale v metodě `outInvoicesMatchingByBank` se použije hodnota v `$this->daysBack`, kde je nastavený pouze 1 den, s hodnotou z konfiguračního souboru se nikde nepracuje.

**Comment by Antis0cial** [comment]
Možná oprava:
```
public function outInvoicesMatchingByBank()
{
    $this->getInvoicer();
    $daysBack = empty($this->config['DAYS_BACK']) ? $this->daysBack : intval($this->config['DAYS_BACK']);
    foreach ($this->getPaymentsToProcess($daysBack, 'in') as $paymentData) {
        ...
```

**Comment by Vitexus** [comment]
Snažím se tu classu mít pokud možno univerzální tak ten den nabiju rovnou v hlavním skriptu. Doufám že se to bude chovat podle vašich představ, protože já tenhle skript moc nepoužívám. Místo něj používám ParujFakuryNew2Old.php který si platby k párování "ukusuje" po dnech.
Z chvíli bude vybuildovaný balíček. To sem jětě taky napíšu.

**Comment by Vitexus** [comment]
Hotovo:
https://www.vitexsoftware.cz/package.php?package=php-flexibee-matcher
Prosím vyzkoušejte.
V ideálním případě by mělo stačit **apt update && apt upgrade**
